# Generated by Django 5.0.2 on 2024-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbusers', '0003_gallery_remove_galleryimage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
