# Generated by Django 5.0.2 on 2024-11-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbusers', '0004_gallery_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
    ]
